In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_column', 400)
pd.set_option('display.max_rows', 100)

In [3]:
train_A=pd.read_csv("sample_submission_M0L0uXE.csv")
train_B=pd.read_csv("test_2umaH9m.csv")
train_C=pd.read_csv("train_LZdllcl.csv")

In [4]:
print(train_A.shape)
print(train_B.shape)
print(train_C.shape)

(23490, 2)
(23490, 13)
(54808, 14)


In [5]:
train_A.head()


employee_id  is_promoted
0         8724            0
1        74430            0
2        72255            0
3        38562            0
4        64486            0

In [6]:
train_B.head()

employee_id         department     region   education gender  \
0         8724         Technology  region_26  Bachelor's      m   
1        74430                 HR   region_4  Bachelor's      f   
2        72255  Sales & Marketing  region_13  Bachelor's      m   
3        38562        Procurement   region_2  Bachelor's      f   
4        64486            Finance  region_29  Bachelor's      m   

  recruitment_channel  no_of_trainings  age  previous_year_rating  \
0            sourcing                1   24                   NaN   
1               other                1   31                   3.0   
2               other                1   31                   1.0   
3               other                3   31                   2.0   
4            sourcing                1   30                   4.0   

   length_of_service  KPIs_met >80%  awards_won?  avg_training_score  
0                  1              1            0                  77  
1                  5              0            0                  51  
2                  4              0            0                  47  
3                  9              0            0                  65  
4                  7              0            0                  61

In [7]:
train_C.head()


employee_id         department     region         education gender  \
0        65438  Sales & Marketing   region_7  Master's & above      f   
1        65141         Operations  region_22        Bachelor's      m   
2         7513  Sales & Marketing  region_19        Bachelor's      m   
3         2542  Sales & Marketing  region_23        Bachelor's      m   
4        48945         Technology  region_26        Bachelor's      m   

  recruitment_channel  no_of_trainings  age  previous_year_rating  \
0            sourcing                1   35                   5.0   
1               other                1   30                   5.0   
2            sourcing                1   34                   3.0   
3               other                2   39                   1.0   
4               other                1   45                   3.0   

   length_of_service  KPIs_met >80%  awards_won?  avg_training_score  \
0                  8              1            0                  49   
1                  4              0            0                  60   
2                  7              0            0                  50   
3                 10              0            0                  50   
4                  2              0            0                  73   

   is_promoted  
0            0  
1            0  
2            0  
3            0  
4            0

In [8]:
#To fill the missing NaN values 
train_B= train_B.fillna(-999)
train_C= train_C.fillna(-999)

In [9]:
y = train_C['is_promoted']
X = train_C.drop(columns=['is_promoted'])


In [10]:
not_pro=train_C[y==0]
promote=train_C[y==1]

In [11]:
print(promote.shape)
print(not_pro.shape)

(4668, 14)
(50140, 14)


for test data

In [12]:
X_train_B = train_B

In [ ]:
#preprocessing
"""from sklearn import preprocessing
for f in X.columns:
    if X[f].dtype=='object' :
        lbl = preprocessing.LabelEncoder()
        lbl.fit(list(X[f].values))
        X[f] = lbl.transform(list(X[f].values))

In [14]:
from sklearn import preprocessing
for f in X.columns:
  if X[f].dtype=='object' :
        lbl = preprocessing.LabelEncoder()
        lbl.fit(list(X[f].values))
        X[f] = lbl.transform(list(X[f].values))
        X_train_B[f] = lbl.transform(list(X_train_B[f].values))

In [ ]:
"""from sklearn.preprocessing import StandardScaler
SC_X=StandardScaler().fit_transform(X)

In [15]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
#sc.fit(X)
SC_X=sc.fit_transform(X)
SC_X_train_B=sc.transform(X_train_B)

In [ ]:
"""from sklearn.decomposition import PCA
pca = PCA(n_components=0.99999)
PC_X = pca.fit_transform(SC_X)

In [16]:
from sklearn.decomposition import PCA
pca = PCA(n_components=0.99999)
#pca.fit(SC_X)
PC_X = pca.fit_transform(SC_X)
PC_X_train_B = pca.transform(SC_X_train_B)

As you can see in above cell , our dataset is imbalanced data , so in this phase of cell we balanced our data .

In [17]:
#solving class imbalancy problem
#using undersampling method
from imblearn.under_sampling import NearMiss

/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)


In [18]:
# implementing undersampling for handling imbalanced
nM = NearMiss(random_state=42)
X_res,y_res=nM.fit_resample(PC_X,y)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [19]:
X_res.shape,y_res.shape

((9336, 13), (9336,))

In [20]:
from collections import Counter
print('Original dataset shape {}'.format(Counter(y)))
print('Resampled dataset shape {}'.format(Counter(y_res)))

Original dataset shape Counter({0: 50140, 1: 4668})
Resampled dataset shape Counter({0: 4668, 1: 4668})


In [21]:
# RandomOverSample to handle imbalanced data
from imblearn.over_sampling import RandomOverSampler


In [22]:
os = RandomOverSampler(ratio=1)

X_res,y_res=os.fit_sample(PC_X,y)


/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [23]:
X_res.shape,y_res.shape



((100280, 13), (100280,))

In [24]:
from collections import Counter
print('Original data set {}'.format(Counter(y)))
print('Resampled data set {}'.format(Counter(y_res)))

Original data set Counter({0: 50140, 1: 4668})
Resampled data set Counter({0: 50140, 1: 50140})


In [ ]:
# solving class imbalancy problem 
# using over sampling method
from imblearn.combine import SMOTETomek


In [ ]:
# implementing Oversampling for Handling Imbalanced
smk = SMOTETomek(random_state=10)
X_res,y_res=smk.fit_sample(PC_X,y)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
X_res.shape,y_res.shape

((99684, 13), (99684,))

In [ ]:
from collections import Counter
print('Original dataset shape {} '.format(Counter(y)))
print('Resampled dataset shape []'.format(Counter(y_res)))

Original dataset shape Counter({0: 50140, 1: 4668}) 
Resampled dataset shape []


In [25]:
#try
# FEATURE SELECTION
#Automatic implementations of Backward Elimination in Python with p-value
import statsmodels.api as sm
def backwardElimination(y,x,sl,x_test):
    numVars = len(x[0])
    numRows = len(x)
    x = np.append(arr = np.ones( (numRows,1) ).astype(int), values=x, axis=1)
    x_test = np.append(arr = np.ones( (len(x_test),1) ).astype(int), values=x_test, axis=1)
    for i in range(0, numVars):
        print(i,end=' ')
        numVars = len(x[0])
        regressor_OLS = sm.OLS(y, x).fit()
        pVal=regressor_OLS.pvalues.astype(float)
        maxVar = max(pVal)
        if maxVar > sl:
            for j in range(0, numVars):
                if (pVal[j] == maxVar):
                    x = np.delete(x, j, 1)
                    x_test = np.delete(x_test, j, 1)
                    break;
        else:
            break
    print('sup')
    regressor_OLS.summary()
    return x,x_test
x_opt,x_test=backwardElimination(y_res,X_res,0.05,PC_X_train_B)

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


0 1 sup


In [26]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_opt, y_res, test_size = 0.2, random_state = 0)



LOGISTIC REGRESSION

In [27]:
# algo number 1
# classification  -> logistic regression

from sklearn import  linear_model,metrics 

     
# create logistic regression object 
logReg = linear_model.LogisticRegression(max_iter=1000)

   
# train the model using the training sets 
logReg.fit(X_train,y_train)
  
# making predictions on the testing set
y_pred =logReg.predict(X_test) 

   



this itearation is for test data set i.e train_B

In [28]:
y_pred_B =logReg.predict(x_test) #for test data set i.e train_B

In [29]:
# comparing actual response values (y_test) with predicted response values (y_pred) 

from sklearn.metrics import confusion_matrix

print("confusion metrics =")
confuse= confusion_matrix(y_test,y_pred)
print(confuse)

print("Logistic Regression model accuracy(in %):", metrics.accuracy_score(y_test,y_pred)*100)

print("loss =\n",metrics.log_loss(y_test,y_pred))



confusion metrics =
[[6953 3028]
 [2757 7318]]
Logistic Regression model accuracy(in %): 71.15576386118867
loss =
 9.962566943836105


In [30]:
from sklearn.metrics import f1_score
print(f1_score(y_test,y_pred))


0.7167131874051221


SUPPORT VECTOR MACHINE

In [31]:
# Training the SVM model on the Training set
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)



SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [32]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
print("confusion metrics =")
cm = confusion_matrix(y_test, y_pred)
print(cm)

print("SVM ALGORITHM'S accuracy(in %):",accuracy_score(y_test, y_pred)*100)

print("LOSS LOG =\n",metrics.log_loss(y_test,y_pred))

confusion metrics =
[[6749 3232]
 [2584 7491]]
SVM ALGORITHM'S accuracy(in %): 71.00119664938173
LOSS LOG =
 10.015960700623003


In [33]:
from sklearn.metrics import f1_score
f1_score(y_test,y_pred)

0.7203577267044908

KERNEL SVM

In [44]:
# Training the Kernel SVM model on the Training set
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [45]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
print("confusion metrics =")
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(" KERNEL SVM ALGORITHM'S accuracy(in %):",accuracy_score(y_test, y_pred)*100)

print("LOSS LOG =\n",metrics.log_loss(y_test,y_pred))

confusion metrics =
[[6737 3244]
 [1457 8618]]
 KERNEL SVM ALGORITHM'S accuracy(in %): 76.56063023534104
LOSS LOG =
 8.095800843963834


In [46]:
from sklearn.metrics import f1_score
f1_score(y_test,y_pred)

0.78570451748188

DECISION TREE

In [47]:
# Training the Decision Tree Classification model on the Training set
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)



DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [48]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
print("confusion metrics =")
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("DECISION TREE ALGORITHM'S accuracy(in %):",accuracy_score(y_test, y_pred)*100)

print("LOSS LOG =\n",metrics.log_loss(y_test,y_pred))

confusion metrics =
[[ 9282   699]
 [    0 10075]]
DECISION TREE ALGORITHM'S accuracy(in %): 96.51475867570801
LOSS LOG =
 1.2037875757202976


In [49]:
from sklearn.metrics import f1_score
f1_score(y_test,y_pred)

0.9664732121444674

RANDOM FOREST

In [50]:
# Training the Random Forest Classification model on the Training set
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)



RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [51]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
print("confusion metrics =")
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("RANDOM FOREST ALGORITHM'S accuracy(in %):",accuracy_score(y_test, y_pred)*100)

print("LOSS LOG =\n",metrics.log_loss(y_test,y_pred))

confusion metrics =
[[ 9724   257]
 [    3 10072]]
RANDOM FOREST ALGORITHM'S accuracy(in %): 98.70362983645792
LOSS LOG =
 0.4477606381739308


In [52]:
from sklearn.metrics import f1_score
f1_score(y_test,y_pred)

0.987257400509704

This iteration in done for calculating the predicted value for test dataset of train_B data set.

In [57]:
#for test data set i.e train_B
y_pred_B =classifier.predict(x_test) 

This cell is used to make .csv file for submission of test data

In [58]:
#converting into csv file and representing y-predicted values in data frame for train_B data set of test data .
final_result_df=pd.DataFrame({'employee_id':train_B.iloc[:,0].values,'is_promoted':y_pred_B})
final_result_df.to_csv('Predicted_test.csv',index=False)